import {IBM_Plex_Sans} from "next/font/google";
import "./globals.css";
import {Header} from "@/components/Header";
import {Footer} from "@/components/Footer";

const ibm = IBM_Plex_Sans({
  variable: "--font-ibm",
  weight: ['300','400','500', '600', '700'],
  subsets: ["cyrillic", "latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className = {`${ibm.variable} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
